/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProRouteImport } from './routes/pro'
import { Route as MetaRouteImport } from './routes/meta'
import { Route as LeaguesRouteImport } from './routes/leagues'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as HeroesRouteImport } from './routes/heroes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MetaIndexRouteImport } from './routes/meta.index'
import { Route as TeamTeamIdRouteImport } from './routes/team.$teamId'
import { Route as PlayerAccountIdRouteImport } from './routes/player.$accountId'
import { Route as MetaBracketRouteImport } from './routes/meta.$bracket'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as LeagueLeagueIdRouteImport } from './routes/league.$leagueId'
import { Route as HeroHeroNameRouteImport } from './routes/hero.$heroName'
import { Route as MatchMatchIdIndexRouteImport } from './routes/match.$matchId.index'
import { Route as MatchMatchIdTabRouteImport } from './routes/match.$matchId.$tab'

const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaRoute = MetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesRoute = LeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesRoute = HeroesRouteImport.update({
  id: '/heroes',
  path: '/heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaIndexRoute = MetaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MetaRoute,
} as any)
const TeamTeamIdRoute = TeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerAccountIdRoute = PlayerAccountIdRouteImport.update({
  id: '/player/$accountId',
  path: '/player/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaBracketRoute = MetaBracketRouteImport.update({
  id: '/$bracket',
  path: '/$bracket',
  getParentRoute: () => MetaRoute,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdRoute = LeagueLeagueIdRouteImport.update({
  id: '/league/$leagueId',
  path: '/league/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroHeroNameRoute = HeroHeroNameRouteImport.update({
  id: '/hero/$heroName',
  path: '/hero/$heroName',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdIndexRoute = MatchMatchIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatchMatchIdRoute,
} as any)
const MatchMatchIdTabRoute = MatchMatchIdTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => MatchMatchIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/heroes': typeof HeroesRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/leagues': typeof LeaguesRoute
  '/meta': typeof MetaRouteWithChildren
  '/pro': typeof ProRoute
  '/hero/$heroName': typeof HeroHeroNameRoute
  '/league/$leagueId': typeof LeagueLeagueIdRoute
  '/match/$matchId': typeof MatchMatchIdRouteWithChildren
  '/meta/$bracket': typeof MetaBracketRoute
  '/player/$accountId': typeof PlayerAccountIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/meta/': typeof MetaIndexRoute
  '/match/$matchId/$tab': typeof MatchMatchIdTabRoute
  '/match/$matchId/': typeof MatchMatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/heroes': typeof HeroesRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/leagues': typeof LeaguesRoute
  '/pro': typeof ProRoute
  '/hero/$heroName': typeof HeroHeroNameRoute
  '/league/$leagueId': typeof LeagueLeagueIdRoute
  '/meta/$bracket': typeof MetaBracketRoute
  '/player/$accountId': typeof PlayerAccountIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/meta': typeof MetaIndexRoute
  '/match/$matchId/$tab': typeof MatchMatchIdTabRoute
  '/match/$matchId': typeof MatchMatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/heroes': typeof HeroesRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/leagues': typeof LeaguesRoute
  '/meta': typeof MetaRouteWithChildren
  '/pro': typeof ProRoute
  '/hero/$heroName': typeof HeroHeroNameRoute
  '/league/$leagueId': typeof LeagueLeagueIdRoute
  '/match/$matchId': typeof MatchMatchIdRouteWithChildren
  '/meta/$bracket': typeof MetaBracketRoute
  '/player/$accountId': typeof PlayerAccountIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/meta/': typeof MetaIndexRoute
  '/match/$matchId/$tab': typeof MatchMatchIdTabRoute
  '/match/$matchId/': typeof MatchMatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/heroes'
    | '/leaderboards'
    | '/leagues'
    | '/meta'
    | '/pro'
    | '/hero/$heroName'
    | '/league/$leagueId'
    | '/match/$matchId'
    | '/meta/$bracket'
    | '/player/$accountId'
    | '/team/$teamId'
    | '/meta/'
    | '/match/$matchId/$tab'
    | '/match/$matchId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/heroes'
    | '/leaderboards'
    | '/leagues'
    | '/pro'
    | '/hero/$heroName'
    | '/league/$leagueId'
    | '/meta/$bracket'
    | '/player/$accountId'
    | '/team/$teamId'
    | '/meta'
    | '/match/$matchId/$tab'
    | '/match/$matchId'
  id:
    | '__root__'
    | '/'
    | '/heroes'
    | '/leaderboards'
    | '/leagues'
    | '/meta'
    | '/pro'
    | '/hero/$heroName'
    | '/league/$leagueId'
    | '/match/$matchId'
    | '/meta/$bracket'
    | '/player/$accountId'
    | '/team/$teamId'
    | '/meta/'
    | '/match/$matchId/$tab'
    | '/match/$matchId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HeroesRoute: typeof HeroesRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  LeaguesRoute: typeof LeaguesRoute
  MetaRoute: typeof MetaRouteWithChildren
  ProRoute: typeof ProRoute
  HeroHeroNameRoute: typeof HeroHeroNameRoute
  LeagueLeagueIdRoute: typeof LeagueLeagueIdRoute
  MatchMatchIdRoute: typeof MatchMatchIdRouteWithChildren
  PlayerAccountIdRoute: typeof PlayerAccountIdRoute
  TeamTeamIdRoute: typeof TeamTeamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta': {
      id: '/meta'
      path: '/meta'
      fullPath: '/meta'
      preLoaderRoute: typeof MetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues': {
      id: '/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof LeaguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes': {
      id: '/heroes'
      path: '/heroes'
      fullPath: '/heroes'
      preLoaderRoute: typeof HeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta/': {
      id: '/meta/'
      path: '/'
      fullPath: '/meta/'
      preLoaderRoute: typeof MetaIndexRouteImport
      parentRoute: typeof MetaRoute
    }
    '/team/$teamId': {
      id: '/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof TeamTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$accountId': {
      id: '/player/$accountId'
      path: '/player/$accountId'
      fullPath: '/player/$accountId'
      preLoaderRoute: typeof PlayerAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta/$bracket': {
      id: '/meta/$bracket'
      path: '/$bracket'
      fullPath: '/meta/$bracket'
      preLoaderRoute: typeof MetaBracketRouteImport
      parentRoute: typeof MetaRoute
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId': {
      id: '/league/$leagueId'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId'
      preLoaderRoute: typeof LeagueLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero/$heroName': {
      id: '/hero/$heroName'
      path: '/hero/$heroName'
      fullPath: '/hero/$heroName'
      preLoaderRoute: typeof HeroHeroNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId/': {
      id: '/match/$matchId/'
      path: '/'
      fullPath: '/match/$matchId/'
      preLoaderRoute: typeof MatchMatchIdIndexRouteImport
      parentRoute: typeof MatchMatchIdRoute
    }
    '/match/$matchId/$tab': {
      id: '/match/$matchId/$tab'
      path: '/$tab'
      fullPath: '/match/$matchId/$tab'
      preLoaderRoute: typeof MatchMatchIdTabRouteImport
      parentRoute: typeof MatchMatchIdRoute
    }
  }
}

interface MetaRouteChildren {
  MetaBracketRoute: typeof MetaBracketRoute
  MetaIndexRoute: typeof MetaIndexRoute
}

const MetaRouteChildren: MetaRouteChildren = {
  MetaBracketRoute: MetaBracketRoute,
  MetaIndexRoute: MetaIndexRoute,
}

const MetaRouteWithChildren = MetaRoute._addFileChildren(MetaRouteChildren)

interface MatchMatchIdRouteChildren {
  MatchMatchIdTabRoute: typeof MatchMatchIdTabRoute
  MatchMatchIdIndexRoute: typeof MatchMatchIdIndexRoute
}

const MatchMatchIdRouteChildren: MatchMatchIdRouteChildren = {
  MatchMatchIdTabRoute: MatchMatchIdTabRoute,
  MatchMatchIdIndexRoute: MatchMatchIdIndexRoute,
}

const MatchMatchIdRouteWithChildren = MatchMatchIdRoute._addFileChildren(
  MatchMatchIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HeroesRoute: HeroesRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  LeaguesRoute: LeaguesRoute,
  MetaRoute: MetaRouteWithChildren,
  ProRoute: ProRoute,
  HeroHeroNameRoute: HeroHeroNameRoute,
  LeagueLeagueIdRoute: LeagueLeagueIdRoute,
  MatchMatchIdRoute: MatchMatchIdRouteWithChildren,
  PlayerAccountIdRoute: PlayerAccountIdRoute,
  TeamTeamIdRoute: TeamTeamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
