/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProMetaRouteImport } from './routes/pro-meta'
import { Route as ProRouteImport } from './routes/pro'
import { Route as MetaRouteImport } from './routes/meta'
import { Route as LeaguesRouteImport } from './routes/leagues'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as HeroesRouteImport } from './routes/heroes'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MetaIndexRouteImport } from './routes/meta.index'
import { Route as LeaderboardsIndexRouteImport } from './routes/leaderboards.index'
import { Route as ExploreIndexRouteImport } from './routes/explore.index'
import { Route as TeamTeamIdRouteImport } from './routes/team.$teamId'
import { Route as PlayerAccountIdRouteImport } from './routes/player.$accountId'
import { Route as MetaBracketRouteImport } from './routes/meta.$bracket'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as LeagueLeagueIdRouteImport } from './routes/league.$leagueId'
import { Route as LeaderboardsRegionRouteImport } from './routes/leaderboards.$region'
import { Route as HeroHeroNameRouteImport } from './routes/hero.$heroName'
import { Route as ExploreRecordsRouteImport } from './routes/explore.records'
import { Route as PlayerAccountIdIndexRouteImport } from './routes/player.$accountId.index'
import { Route as MatchMatchIdIndexRouteImport } from './routes/match.$matchId.index'
import { Route as LeagueLeagueIdIndexRouteImport } from './routes/league.$leagueId.index'
import { Route as PlayerAccountIdStatsRouteImport } from './routes/player.$accountId.stats'
import { Route as PlayerAccountIdProfileRouteImport } from './routes/player.$accountId.profile'
import { Route as PlayerAccountIdMatchesRouteImport } from './routes/player.$accountId.matches'
import { Route as MatchMatchIdTabRouteImport } from './routes/match.$matchId.$tab'
import { Route as LeagueLeagueIdResultsRouteImport } from './routes/league.$leagueId.results'
import { Route as LeagueLeagueIdTabRouteImport } from './routes/league.$leagueId.$tab'
import { Route as PlayerAccountIdProfileIndexRouteImport } from './routes/player.$accountId.profile.index'
import { Route as LeagueLeagueIdResultsIndexRouteImport } from './routes/league.$leagueId.results.index'
import { Route as PlayerAccountIdProfileFeedRouteImport } from './routes/player.$accountId.profile.$feed'
import { Route as LeagueLeagueIdResultsViewRouteImport } from './routes/league.$leagueId.results.$view'

const ProMetaRoute = ProMetaRouteImport.update({
  id: '/pro-meta',
  path: '/pro-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaRoute = MetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesRoute = LeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesRoute = HeroesRouteImport.update({
  id: '/heroes',
  path: '/heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaIndexRoute = MetaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MetaRoute,
} as any)
const LeaderboardsIndexRoute = LeaderboardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeaderboardsRoute,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExploreRoute,
} as any)
const TeamTeamIdRoute = TeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerAccountIdRoute = PlayerAccountIdRouteImport.update({
  id: '/player/$accountId',
  path: '/player/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaBracketRoute = MetaBracketRouteImport.update({
  id: '/$bracket',
  path: '/$bracket',
  getParentRoute: () => MetaRoute,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdRoute = LeagueLeagueIdRouteImport.update({
  id: '/league/$leagueId',
  path: '/league/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRegionRoute = LeaderboardsRegionRouteImport.update({
  id: '/$region',
  path: '/$region',
  getParentRoute: () => LeaderboardsRoute,
} as any)
const HeroHeroNameRoute = HeroHeroNameRouteImport.update({
  id: '/hero/$heroName',
  path: '/hero/$heroName',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRecordsRoute = ExploreRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => ExploreRoute,
} as any)
const PlayerAccountIdIndexRoute = PlayerAccountIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayerAccountIdRoute,
} as any)
const MatchMatchIdIndexRoute = MatchMatchIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatchMatchIdRoute,
} as any)
const LeagueLeagueIdIndexRoute = LeagueLeagueIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeagueLeagueIdRoute,
} as any)
const PlayerAccountIdStatsRoute = PlayerAccountIdStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => PlayerAccountIdRoute,
} as any)
const PlayerAccountIdProfileRoute = PlayerAccountIdProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PlayerAccountIdRoute,
} as any)
const PlayerAccountIdMatchesRoute = PlayerAccountIdMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => PlayerAccountIdRoute,
} as any)
const MatchMatchIdTabRoute = MatchMatchIdTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => MatchMatchIdRoute,
} as any)
const LeagueLeagueIdResultsRoute = LeagueLeagueIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => LeagueLeagueIdRoute,
} as any)
const LeagueLeagueIdTabRoute = LeagueLeagueIdTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => LeagueLeagueIdRoute,
} as any)
const PlayerAccountIdProfileIndexRoute =
  PlayerAccountIdProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PlayerAccountIdProfileRoute,
  } as any)
const LeagueLeagueIdResultsIndexRoute =
  LeagueLeagueIdResultsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LeagueLeagueIdResultsRoute,
  } as any)
const PlayerAccountIdProfileFeedRoute =
  PlayerAccountIdProfileFeedRouteImport.update({
    id: '/$feed',
    path: '/$feed',
    getParentRoute: () => PlayerAccountIdProfileRoute,
  } as any)
const LeagueLeagueIdResultsViewRoute =
  LeagueLeagueIdResultsViewRouteImport.update({
    id: '/$view',
    path: '/$view',
    getParentRoute: () => LeagueLeagueIdResultsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteWithChildren
  '/heroes': typeof HeroesRoute
  '/leaderboards': typeof LeaderboardsRouteWithChildren
  '/leagues': typeof LeaguesRoute
  '/meta': typeof MetaRouteWithChildren
  '/pro': typeof ProRoute
  '/pro-meta': typeof ProMetaRoute
  '/explore/records': typeof ExploreRecordsRoute
  '/hero/$heroName': typeof HeroHeroNameRoute
  '/leaderboards/$region': typeof LeaderboardsRegionRoute
  '/league/$leagueId': typeof LeagueLeagueIdRouteWithChildren
  '/match/$matchId': typeof MatchMatchIdRouteWithChildren
  '/meta/$bracket': typeof MetaBracketRoute
  '/player/$accountId': typeof PlayerAccountIdRouteWithChildren
  '/team/$teamId': typeof TeamTeamIdRoute
  '/explore/': typeof ExploreIndexRoute
  '/leaderboards/': typeof LeaderboardsIndexRoute
  '/meta/': typeof MetaIndexRoute
  '/league/$leagueId/$tab': typeof LeagueLeagueIdTabRoute
  '/league/$leagueId/results': typeof LeagueLeagueIdResultsRouteWithChildren
  '/match/$matchId/$tab': typeof MatchMatchIdTabRoute
  '/player/$accountId/matches': typeof PlayerAccountIdMatchesRoute
  '/player/$accountId/profile': typeof PlayerAccountIdProfileRouteWithChildren
  '/player/$accountId/stats': typeof PlayerAccountIdStatsRoute
  '/league/$leagueId/': typeof LeagueLeagueIdIndexRoute
  '/match/$matchId/': typeof MatchMatchIdIndexRoute
  '/player/$accountId/': typeof PlayerAccountIdIndexRoute
  '/league/$leagueId/results/$view': typeof LeagueLeagueIdResultsViewRoute
  '/player/$accountId/profile/$feed': typeof PlayerAccountIdProfileFeedRoute
  '/league/$leagueId/results/': typeof LeagueLeagueIdResultsIndexRoute
  '/player/$accountId/profile/': typeof PlayerAccountIdProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/heroes': typeof HeroesRoute
  '/leagues': typeof LeaguesRoute
  '/pro': typeof ProRoute
  '/pro-meta': typeof ProMetaRoute
  '/explore/records': typeof ExploreRecordsRoute
  '/hero/$heroName': typeof HeroHeroNameRoute
  '/leaderboards/$region': typeof LeaderboardsRegionRoute
  '/meta/$bracket': typeof MetaBracketRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/explore': typeof ExploreIndexRoute
  '/leaderboards': typeof LeaderboardsIndexRoute
  '/meta': typeof MetaIndexRoute
  '/league/$leagueId/$tab': typeof LeagueLeagueIdTabRoute
  '/match/$matchId/$tab': typeof MatchMatchIdTabRoute
  '/player/$accountId/matches': typeof PlayerAccountIdMatchesRoute
  '/player/$accountId/stats': typeof PlayerAccountIdStatsRoute
  '/league/$leagueId': typeof LeagueLeagueIdIndexRoute
  '/match/$matchId': typeof MatchMatchIdIndexRoute
  '/player/$accountId': typeof PlayerAccountIdIndexRoute
  '/league/$leagueId/results/$view': typeof LeagueLeagueIdResultsViewRoute
  '/player/$accountId/profile/$feed': typeof PlayerAccountIdProfileFeedRoute
  '/league/$leagueId/results': typeof LeagueLeagueIdResultsIndexRoute
  '/player/$accountId/profile': typeof PlayerAccountIdProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteWithChildren
  '/heroes': typeof HeroesRoute
  '/leaderboards': typeof LeaderboardsRouteWithChildren
  '/leagues': typeof LeaguesRoute
  '/meta': typeof MetaRouteWithChildren
  '/pro': typeof ProRoute
  '/pro-meta': typeof ProMetaRoute
  '/explore/records': typeof ExploreRecordsRoute
  '/hero/$heroName': typeof HeroHeroNameRoute
  '/leaderboards/$region': typeof LeaderboardsRegionRoute
  '/league/$leagueId': typeof LeagueLeagueIdRouteWithChildren
  '/match/$matchId': typeof MatchMatchIdRouteWithChildren
  '/meta/$bracket': typeof MetaBracketRoute
  '/player/$accountId': typeof PlayerAccountIdRouteWithChildren
  '/team/$teamId': typeof TeamTeamIdRoute
  '/explore/': typeof ExploreIndexRoute
  '/leaderboards/': typeof LeaderboardsIndexRoute
  '/meta/': typeof MetaIndexRoute
  '/league/$leagueId/$tab': typeof LeagueLeagueIdTabRoute
  '/league/$leagueId/results': typeof LeagueLeagueIdResultsRouteWithChildren
  '/match/$matchId/$tab': typeof MatchMatchIdTabRoute
  '/player/$accountId/matches': typeof PlayerAccountIdMatchesRoute
  '/player/$accountId/profile': typeof PlayerAccountIdProfileRouteWithChildren
  '/player/$accountId/stats': typeof PlayerAccountIdStatsRoute
  '/league/$leagueId/': typeof LeagueLeagueIdIndexRoute
  '/match/$matchId/': typeof MatchMatchIdIndexRoute
  '/player/$accountId/': typeof PlayerAccountIdIndexRoute
  '/league/$leagueId/results/$view': typeof LeagueLeagueIdResultsViewRoute
  '/player/$accountId/profile/$feed': typeof PlayerAccountIdProfileFeedRoute
  '/league/$leagueId/results/': typeof LeagueLeagueIdResultsIndexRoute
  '/player/$accountId/profile/': typeof PlayerAccountIdProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/heroes'
    | '/leaderboards'
    | '/leagues'
    | '/meta'
    | '/pro'
    | '/pro-meta'
    | '/explore/records'
    | '/hero/$heroName'
    | '/leaderboards/$region'
    | '/league/$leagueId'
    | '/match/$matchId'
    | '/meta/$bracket'
    | '/player/$accountId'
    | '/team/$teamId'
    | '/explore/'
    | '/leaderboards/'
    | '/meta/'
    | '/league/$leagueId/$tab'
    | '/league/$leagueId/results'
    | '/match/$matchId/$tab'
    | '/player/$accountId/matches'
    | '/player/$accountId/profile'
    | '/player/$accountId/stats'
    | '/league/$leagueId/'
    | '/match/$matchId/'
    | '/player/$accountId/'
    | '/league/$leagueId/results/$view'
    | '/player/$accountId/profile/$feed'
    | '/league/$leagueId/results/'
    | '/player/$accountId/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/heroes'
    | '/leagues'
    | '/pro'
    | '/pro-meta'
    | '/explore/records'
    | '/hero/$heroName'
    | '/leaderboards/$region'
    | '/meta/$bracket'
    | '/team/$teamId'
    | '/explore'
    | '/leaderboards'
    | '/meta'
    | '/league/$leagueId/$tab'
    | '/match/$matchId/$tab'
    | '/player/$accountId/matches'
    | '/player/$accountId/stats'
    | '/league/$leagueId'
    | '/match/$matchId'
    | '/player/$accountId'
    | '/league/$leagueId/results/$view'
    | '/player/$accountId/profile/$feed'
    | '/league/$leagueId/results'
    | '/player/$accountId/profile'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/heroes'
    | '/leaderboards'
    | '/leagues'
    | '/meta'
    | '/pro'
    | '/pro-meta'
    | '/explore/records'
    | '/hero/$heroName'
    | '/leaderboards/$region'
    | '/league/$leagueId'
    | '/match/$matchId'
    | '/meta/$bracket'
    | '/player/$accountId'
    | '/team/$teamId'
    | '/explore/'
    | '/leaderboards/'
    | '/meta/'
    | '/league/$leagueId/$tab'
    | '/league/$leagueId/results'
    | '/match/$matchId/$tab'
    | '/player/$accountId/matches'
    | '/player/$accountId/profile'
    | '/player/$accountId/stats'
    | '/league/$leagueId/'
    | '/match/$matchId/'
    | '/player/$accountId/'
    | '/league/$leagueId/results/$view'
    | '/player/$accountId/profile/$feed'
    | '/league/$leagueId/results/'
    | '/player/$accountId/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  HeroesRoute: typeof HeroesRoute
  LeaderboardsRoute: typeof LeaderboardsRouteWithChildren
  LeaguesRoute: typeof LeaguesRoute
  MetaRoute: typeof MetaRouteWithChildren
  ProRoute: typeof ProRoute
  ProMetaRoute: typeof ProMetaRoute
  HeroHeroNameRoute: typeof HeroHeroNameRoute
  LeagueLeagueIdRoute: typeof LeagueLeagueIdRouteWithChildren
  MatchMatchIdRoute: typeof MatchMatchIdRouteWithChildren
  PlayerAccountIdRoute: typeof PlayerAccountIdRouteWithChildren
  TeamTeamIdRoute: typeof TeamTeamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pro-meta': {
      id: '/pro-meta'
      path: '/pro-meta'
      fullPath: '/pro-meta'
      preLoaderRoute: typeof ProMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta': {
      id: '/meta'
      path: '/meta'
      fullPath: '/meta'
      preLoaderRoute: typeof MetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues': {
      id: '/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof LeaguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes': {
      id: '/heroes'
      path: '/heroes'
      fullPath: '/heroes'
      preLoaderRoute: typeof HeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta/': {
      id: '/meta/'
      path: '/'
      fullPath: '/meta/'
      preLoaderRoute: typeof MetaIndexRouteImport
      parentRoute: typeof MetaRoute
    }
    '/leaderboards/': {
      id: '/leaderboards/'
      path: '/'
      fullPath: '/leaderboards/'
      preLoaderRoute: typeof LeaderboardsIndexRouteImport
      parentRoute: typeof LeaderboardsRoute
    }
    '/explore/': {
      id: '/explore/'
      path: '/'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/team/$teamId': {
      id: '/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof TeamTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$accountId': {
      id: '/player/$accountId'
      path: '/player/$accountId'
      fullPath: '/player/$accountId'
      preLoaderRoute: typeof PlayerAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta/$bracket': {
      id: '/meta/$bracket'
      path: '/$bracket'
      fullPath: '/meta/$bracket'
      preLoaderRoute: typeof MetaBracketRouteImport
      parentRoute: typeof MetaRoute
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId': {
      id: '/league/$leagueId'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId'
      preLoaderRoute: typeof LeagueLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards/$region': {
      id: '/leaderboards/$region'
      path: '/$region'
      fullPath: '/leaderboards/$region'
      preLoaderRoute: typeof LeaderboardsRegionRouteImport
      parentRoute: typeof LeaderboardsRoute
    }
    '/hero/$heroName': {
      id: '/hero/$heroName'
      path: '/hero/$heroName'
      fullPath: '/hero/$heroName'
      preLoaderRoute: typeof HeroHeroNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/records': {
      id: '/explore/records'
      path: '/records'
      fullPath: '/explore/records'
      preLoaderRoute: typeof ExploreRecordsRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/player/$accountId/': {
      id: '/player/$accountId/'
      path: '/'
      fullPath: '/player/$accountId/'
      preLoaderRoute: typeof PlayerAccountIdIndexRouteImport
      parentRoute: typeof PlayerAccountIdRoute
    }
    '/match/$matchId/': {
      id: '/match/$matchId/'
      path: '/'
      fullPath: '/match/$matchId/'
      preLoaderRoute: typeof MatchMatchIdIndexRouteImport
      parentRoute: typeof MatchMatchIdRoute
    }
    '/league/$leagueId/': {
      id: '/league/$leagueId/'
      path: '/'
      fullPath: '/league/$leagueId/'
      preLoaderRoute: typeof LeagueLeagueIdIndexRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/player/$accountId/stats': {
      id: '/player/$accountId/stats'
      path: '/stats'
      fullPath: '/player/$accountId/stats'
      preLoaderRoute: typeof PlayerAccountIdStatsRouteImport
      parentRoute: typeof PlayerAccountIdRoute
    }
    '/player/$accountId/profile': {
      id: '/player/$accountId/profile'
      path: '/profile'
      fullPath: '/player/$accountId/profile'
      preLoaderRoute: typeof PlayerAccountIdProfileRouteImport
      parentRoute: typeof PlayerAccountIdRoute
    }
    '/player/$accountId/matches': {
      id: '/player/$accountId/matches'
      path: '/matches'
      fullPath: '/player/$accountId/matches'
      preLoaderRoute: typeof PlayerAccountIdMatchesRouteImport
      parentRoute: typeof PlayerAccountIdRoute
    }
    '/match/$matchId/$tab': {
      id: '/match/$matchId/$tab'
      path: '/$tab'
      fullPath: '/match/$matchId/$tab'
      preLoaderRoute: typeof MatchMatchIdTabRouteImport
      parentRoute: typeof MatchMatchIdRoute
    }
    '/league/$leagueId/results': {
      id: '/league/$leagueId/results'
      path: '/results'
      fullPath: '/league/$leagueId/results'
      preLoaderRoute: typeof LeagueLeagueIdResultsRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/$tab': {
      id: '/league/$leagueId/$tab'
      path: '/$tab'
      fullPath: '/league/$leagueId/$tab'
      preLoaderRoute: typeof LeagueLeagueIdTabRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/player/$accountId/profile/': {
      id: '/player/$accountId/profile/'
      path: '/'
      fullPath: '/player/$accountId/profile/'
      preLoaderRoute: typeof PlayerAccountIdProfileIndexRouteImport
      parentRoute: typeof PlayerAccountIdProfileRoute
    }
    '/league/$leagueId/results/': {
      id: '/league/$leagueId/results/'
      path: '/'
      fullPath: '/league/$leagueId/results/'
      preLoaderRoute: typeof LeagueLeagueIdResultsIndexRouteImport
      parentRoute: typeof LeagueLeagueIdResultsRoute
    }
    '/player/$accountId/profile/$feed': {
      id: '/player/$accountId/profile/$feed'
      path: '/$feed'
      fullPath: '/player/$accountId/profile/$feed'
      preLoaderRoute: typeof PlayerAccountIdProfileFeedRouteImport
      parentRoute: typeof PlayerAccountIdProfileRoute
    }
    '/league/$leagueId/results/$view': {
      id: '/league/$leagueId/results/$view'
      path: '/$view'
      fullPath: '/league/$leagueId/results/$view'
      preLoaderRoute: typeof LeagueLeagueIdResultsViewRouteImport
      parentRoute: typeof LeagueLeagueIdResultsRoute
    }
  }
}

interface ExploreRouteChildren {
  ExploreRecordsRoute: typeof ExploreRecordsRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreRecordsRoute: ExploreRecordsRoute,
  ExploreIndexRoute: ExploreIndexRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

interface LeaderboardsRouteChildren {
  LeaderboardsRegionRoute: typeof LeaderboardsRegionRoute
  LeaderboardsIndexRoute: typeof LeaderboardsIndexRoute
}

const LeaderboardsRouteChildren: LeaderboardsRouteChildren = {
  LeaderboardsRegionRoute: LeaderboardsRegionRoute,
  LeaderboardsIndexRoute: LeaderboardsIndexRoute,
}

const LeaderboardsRouteWithChildren = LeaderboardsRoute._addFileChildren(
  LeaderboardsRouteChildren,
)

interface MetaRouteChildren {
  MetaBracketRoute: typeof MetaBracketRoute
  MetaIndexRoute: typeof MetaIndexRoute
}

const MetaRouteChildren: MetaRouteChildren = {
  MetaBracketRoute: MetaBracketRoute,
  MetaIndexRoute: MetaIndexRoute,
}

const MetaRouteWithChildren = MetaRoute._addFileChildren(MetaRouteChildren)

interface LeagueLeagueIdResultsRouteChildren {
  LeagueLeagueIdResultsViewRoute: typeof LeagueLeagueIdResultsViewRoute
  LeagueLeagueIdResultsIndexRoute: typeof LeagueLeagueIdResultsIndexRoute
}

const LeagueLeagueIdResultsRouteChildren: LeagueLeagueIdResultsRouteChildren = {
  LeagueLeagueIdResultsViewRoute: LeagueLeagueIdResultsViewRoute,
  LeagueLeagueIdResultsIndexRoute: LeagueLeagueIdResultsIndexRoute,
}

const LeagueLeagueIdResultsRouteWithChildren =
  LeagueLeagueIdResultsRoute._addFileChildren(
    LeagueLeagueIdResultsRouteChildren,
  )

interface LeagueLeagueIdRouteChildren {
  LeagueLeagueIdTabRoute: typeof LeagueLeagueIdTabRoute
  LeagueLeagueIdResultsRoute: typeof LeagueLeagueIdResultsRouteWithChildren
  LeagueLeagueIdIndexRoute: typeof LeagueLeagueIdIndexRoute
}

const LeagueLeagueIdRouteChildren: LeagueLeagueIdRouteChildren = {
  LeagueLeagueIdTabRoute: LeagueLeagueIdTabRoute,
  LeagueLeagueIdResultsRoute: LeagueLeagueIdResultsRouteWithChildren,
  LeagueLeagueIdIndexRoute: LeagueLeagueIdIndexRoute,
}

const LeagueLeagueIdRouteWithChildren = LeagueLeagueIdRoute._addFileChildren(
  LeagueLeagueIdRouteChildren,
)

interface MatchMatchIdRouteChildren {
  MatchMatchIdTabRoute: typeof MatchMatchIdTabRoute
  MatchMatchIdIndexRoute: typeof MatchMatchIdIndexRoute
}

const MatchMatchIdRouteChildren: MatchMatchIdRouteChildren = {
  MatchMatchIdTabRoute: MatchMatchIdTabRoute,
  MatchMatchIdIndexRoute: MatchMatchIdIndexRoute,
}

const MatchMatchIdRouteWithChildren = MatchMatchIdRoute._addFileChildren(
  MatchMatchIdRouteChildren,
)

interface PlayerAccountIdProfileRouteChildren {
  PlayerAccountIdProfileFeedRoute: typeof PlayerAccountIdProfileFeedRoute
  PlayerAccountIdProfileIndexRoute: typeof PlayerAccountIdProfileIndexRoute
}

const PlayerAccountIdProfileRouteChildren: PlayerAccountIdProfileRouteChildren =
  {
    PlayerAccountIdProfileFeedRoute: PlayerAccountIdProfileFeedRoute,
    PlayerAccountIdProfileIndexRoute: PlayerAccountIdProfileIndexRoute,
  }

const PlayerAccountIdProfileRouteWithChildren =
  PlayerAccountIdProfileRoute._addFileChildren(
    PlayerAccountIdProfileRouteChildren,
  )

interface PlayerAccountIdRouteChildren {
  PlayerAccountIdMatchesRoute: typeof PlayerAccountIdMatchesRoute
  PlayerAccountIdProfileRoute: typeof PlayerAccountIdProfileRouteWithChildren
  PlayerAccountIdStatsRoute: typeof PlayerAccountIdStatsRoute
  PlayerAccountIdIndexRoute: typeof PlayerAccountIdIndexRoute
}

const PlayerAccountIdRouteChildren: PlayerAccountIdRouteChildren = {
  PlayerAccountIdMatchesRoute: PlayerAccountIdMatchesRoute,
  PlayerAccountIdProfileRoute: PlayerAccountIdProfileRouteWithChildren,
  PlayerAccountIdStatsRoute: PlayerAccountIdStatsRoute,
  PlayerAccountIdIndexRoute: PlayerAccountIdIndexRoute,
}

const PlayerAccountIdRouteWithChildren = PlayerAccountIdRoute._addFileChildren(
  PlayerAccountIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRouteWithChildren,
  HeroesRoute: HeroesRoute,
  LeaderboardsRoute: LeaderboardsRouteWithChildren,
  LeaguesRoute: LeaguesRoute,
  MetaRoute: MetaRouteWithChildren,
  ProRoute: ProRoute,
  ProMetaRoute: ProMetaRoute,
  HeroHeroNameRoute: HeroHeroNameRoute,
  LeagueLeagueIdRoute: LeagueLeagueIdRouteWithChildren,
  MatchMatchIdRoute: MatchMatchIdRouteWithChildren,
  PlayerAccountIdRoute: PlayerAccountIdRouteWithChildren,
  TeamTeamIdRoute: TeamTeamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
