/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProRouteImport } from './routes/pro'
import { Route as MetaRouteImport } from './routes/meta'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as HeroesRouteImport } from './routes/heroes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamTeamIdRouteImport } from './routes/team.$teamId'
import { Route as PlayerAccountIdRouteImport } from './routes/player.$accountId'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as HeroHeroNameRouteImport } from './routes/hero.$heroName'

const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaRoute = MetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesRoute = HeroesRouteImport.update({
  id: '/heroes',
  path: '/heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdRoute = TeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerAccountIdRoute = PlayerAccountIdRouteImport.update({
  id: '/player/$accountId',
  path: '/player/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroHeroNameRoute = HeroHeroNameRouteImport.update({
  id: '/hero/$heroName',
  path: '/hero/$heroName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/heroes': typeof HeroesRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/meta': typeof MetaRoute
  '/pro': typeof ProRoute
  '/hero/$heroName': typeof HeroHeroNameRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/player/$accountId': typeof PlayerAccountIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/heroes': typeof HeroesRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/meta': typeof MetaRoute
  '/pro': typeof ProRoute
  '/hero/$heroName': typeof HeroHeroNameRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/player/$accountId': typeof PlayerAccountIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/heroes': typeof HeroesRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/meta': typeof MetaRoute
  '/pro': typeof ProRoute
  '/hero/$heroName': typeof HeroHeroNameRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/player/$accountId': typeof PlayerAccountIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/heroes'
    | '/leaderboards'
    | '/meta'
    | '/pro'
    | '/hero/$heroName'
    | '/match/$matchId'
    | '/player/$accountId'
    | '/team/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/heroes'
    | '/leaderboards'
    | '/meta'
    | '/pro'
    | '/hero/$heroName'
    | '/match/$matchId'
    | '/player/$accountId'
    | '/team/$teamId'
  id:
    | '__root__'
    | '/'
    | '/heroes'
    | '/leaderboards'
    | '/meta'
    | '/pro'
    | '/hero/$heroName'
    | '/match/$matchId'
    | '/player/$accountId'
    | '/team/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HeroesRoute: typeof HeroesRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  MetaRoute: typeof MetaRoute
  ProRoute: typeof ProRoute
  HeroHeroNameRoute: typeof HeroHeroNameRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  PlayerAccountIdRoute: typeof PlayerAccountIdRoute
  TeamTeamIdRoute: typeof TeamTeamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta': {
      id: '/meta'
      path: '/meta'
      fullPath: '/meta'
      preLoaderRoute: typeof MetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes': {
      id: '/heroes'
      path: '/heroes'
      fullPath: '/heroes'
      preLoaderRoute: typeof HeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId': {
      id: '/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof TeamTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$accountId': {
      id: '/player/$accountId'
      path: '/player/$accountId'
      fullPath: '/player/$accountId'
      preLoaderRoute: typeof PlayerAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero/$heroName': {
      id: '/hero/$heroName'
      path: '/hero/$heroName'
      fullPath: '/hero/$heroName'
      preLoaderRoute: typeof HeroHeroNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HeroesRoute: HeroesRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  MetaRoute: MetaRoute,
  ProRoute: ProRoute,
  HeroHeroNameRoute: HeroHeroNameRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  PlayerAccountIdRoute: PlayerAccountIdRoute,
  TeamTeamIdRoute: TeamTeamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
